config/routes.rb
Rails.application.routes.draw do

  root to: 'high_voltage/pages#show' , id: 'index'

  get "/blog" , to: "blog#index" , as: :blog_index
  get "/blog/*title" , to: "blog#post" , as: :blog_post

  get "sign_out" => "sessions#sign_out"
  get "sign_in"  => "sessions#sign_in"
  post "create_session"  => "sessions#create"
  match "sign_up" => "sessions#sign_up" , :via => [:get ,:post]

  resources :purchases do
    collection do
      get "search" => "purchases#index"
    end
    member do
      get :invoice, to: 'purchase_invoices#show'
      get :order
      get :receive
      get :inventory
    end
  end

  resources :baskets do
    collection do
      get "search" => "baskets#index"
    end
    member do
      get :discount
      post :ean
      get :order
      get :purchase
      get :zero
    end
  end

  resources :houses , :except => [:show , :destroy] do
    collection do
      get :products
    end
  end

  resources :orders , :except => [:edit] do
    collection do
      get "search" => "orders#index"
    end
    member do
      get "mail/:act" , :action => :mail , :as => :mail
      get :pay
      get :shipment
      get :ship
      get :deduct_only
      get :cancel
      patch :shipment
      get :invoice
      get :receipt
      get :slip
      get :reminder
      get :rakennus
      get :ecoframe
      get "finvoice_:num" , action: :finvoice , as: :finvoice
    end
  end

  resources :items do
    collection do
      get "search" => "items#index"
    end
    member do
    end
  end

  resources :categories do
    collection do
      get "search" => "categories#index"
    end
    member do
    end
  end

  resources :products do
    collection do
      get "search" => "products#index"
      get :names
    end
    member do
      get :delete
      get :barcode  #print the barcode and price on a 50x25 mm area
    end
  end

  resources :clerks do
    collection do
      get "search" => "clerks#index"
    end
    member do
    end
  end

  resources :addresses do
    collection do
      get "search" => "addresses#index"
    end
  end

  resources :suppliers do
    collection do
      get "search" => "suppliers#index"
    end
    member do
    end
  end

  get "manage/all" => "manage#all"
  get '/manage/reports' => 'manage#reports'

  get "api/purchase" => "api#purchase" , format: :json

  get "/3d/*id" => 'kolme_d#show' , as: :kolme_d
end

Rails.application.config.after_initialize do |application|
  application.routes.append do
    match '*path', via: :all, to: 'high_voltage/pages#show' , id: "404"#if Rails.production?
  end
end

app/models/basket.rb
class Basket < ActiveRecord::Base
  ADD = 1
  REMOVE = -1

  store :info, accessors: [ :width, :length , :height , :angle , :name] #, coder: JSON
  validates :width, numericality: true , allow_nil: true
  validates :length, numericality: true, allow_nil: true
  validates :height, numericality: true, allow_nil: true
  validates :angle, numericality: true, allow_nil: true

  belongs_to :kori, polymorphic: true  , optional: true #kori is basket in finnish

  belongs_to :order, -> { where(baskets: {kori_type: 'Order'}).includes( :baskets) },
              foreign_key: 'kori_id' , optional: true

  has_many :items, autosave: true , :dependent => :destroy

  default_scope { order('created_at DESC') }

  accepts_nested_attributes_for :items

  after_touch :update_cache

  def quantity
    items.sum(:quantity)
  end

  def empty?
    self.items.empty?
  end

  def locked?
    not self.locked.blank?
  end

  def update_cache
    total_p = (items.to_a.sum{ |i| i.total }).round(2)
    total_t =  (items.to_a.sum{ |i| i.tax_amount}).round(2)
    return if self.total_price == total_p
    update_attributes!(total_price: total_p ,total_tax: total_t)
  end

  #return a hash of rate => amount
  def taxes
    taxes = Hash.new(0.0)
    items.each do |item|
      taxes[item.tax] += item.tax_amount
    end
    taxes
  end

  # receiving the goods means that the item quantity is added to the stock (product.inventory)
  # locks the basket so receiving or deducting becomes an error.
  def receive!
    raise "Locked since #{self.locked}" if locked?
    sum = do_adjust( ADD ) # one for adding products
    self.locked = Date.today
    self.save!
    sum
  end

  # deduct the items from inventory, change affects immediately in the products
  # locks the basket so receiving or deducting becomes an error.
  def deduct!
    raise "Locked since #{self.locked}" if locked?
    sum = do_adjust( REMOVE )
    self.locked = Date.today
    self.save!
    sum
  end

  # return inventory and cancel basket
  # very similar to receive, just we don't change prices (and don't lock)
  def cancel_order!
    self.locked = nil
    do_adjust( ADD )
    self.save!
  end

  # inventorying the basket means setting the item quantity as the stock
  # we actually change the basket for it to be a relative change (so as to look like a receive)
  def inventory!
    self.items.each { |item| item.quantity -= item.product.inventory  }
    self.receive!
  end

  # set all items prices to zero
  def zero_prices!
    raise "Locked since #{self.locked}" if locked?
    self.items.each do |item|
      item.price = 0.0
    end
    self.save!
  end

  def isa typ
    self.kori_type.to_s.downcase == typ.to_s.downcase && self.kori_id != nil
  end

  def suppliers
    ss = items.collect{|i| i.product.supplier if i.product}
    ss.uniq!
    ss.delete(nil)
    ss
  end

  def remove_product(prod)
    raise "Locked since #{self.locked}" if locked?
    item = items.where(:product_id => prod.id ).limit(1).first
    return unless item
    items.delete item
  end
  #when adding a product (with quantity) we ensure there is only one item for each product
  def add_product prod , quant = 1
    return unless prod
    return unless quant != 0
    raise "Locked since #{self.locked}" if locked?
    exists = items.where(:product_id => prod.id ).limit(1).first
    if exists
      exists.quantity += quant
    else
      price = (self.kori_type == "Purchase") ? prod.cost : prod.price
      exists = items.new :quantity => quant , :product => prod , :price => price ,
                         :tax => prod.tax , :name => prod.name
    end
    if( exists.quantity == 0)
      items.delete exists
    else
      exists.save!
    end
    reload
  end

  def amount_for(product)
    house = self
    return nil if product.description.blank?
    begin
      eval(product.description).to_f.round(2)
    rescue Exception => e
      "error #{e.class}"
    end
  end


  def width
    self.info[:width].to_f
  end
  def length
    self.info[:length].to_f
  end
  def height
    self.info[:height].to_f
  end
  def angle
    self.info[:angle].to_f
  end

  def gabel_height
    (roof_length * Math.sin((Math::PI * self.angle) / 180)).round(2)
  end

  def roof_length
    (0.5*self.width / Math.cos((Math::PI * self.angle) / 180)).round(2)
  end

  def end_wall_area
    (self.width * (2*self.height + self.gabel_height)).round(2)
  end

  def inner_length
    self.length - 2 * 0.4
  end

  def inner_width
    self.width - 2 * 0.4
  end

  private

  def do_adjust( multiplier )
    sum = 0
    self.items.each do |item|
      prod = item.product
      prod.inventory = prod.inventory + multiplier * item.quantity
      sum += item.quantity
      prod.save!
    end
    sum
  end

end

app/controllers/baskets_controller.rb
# encoding : utf-8
class BasketsController < AdminController
  include BasketsHelper

  before_action :load_basket, :only => [:show, :edit, :change , :update, :destroy , :order ,
                                         :purchase , :discount , :ean , :zero]

  def index
    @q = Basket.ransack( params[:q] )
    @basket_scope = @q.result( :distinct => true )
    @baskets = @basket_scope.includes({:items => :product} , :kori).page(params[:page] )
  end

  def show
  end

  def zero
    @basket.zero_prices!
    render :edit
  end

  #as an action this order is meant as a verb, ie order this basket
  def order
    if @basket.empty?
      return render :edit , :notice => t(:basket_empty)
    end
    order = Order.create! :basket => @basket , :email => current_clerk.email , :ordered_on => Date.today
    redirect_to order_path(order)
  end

  def purchase
    if @basket.empty?
      render :edit , :notice => t(:basket_empty)
      return
    end
    if @basket.locked
      render :show , :notice => t(:basket_locked)
      return
    end
    purchase = Purchase.create! :basket => @basket
    redirect_to purchase_path(purchase)
  end

  def new
    @basket = Basket.create!
    render :edit
  end

  # refactor discount out of edit
  def discount
    if discount = params[:discount]
      if i_id = params[:item]
        item = @basket.items.find { |it| it.id.to_s == i_id }
        item_discount( item , discount )
      else
        @basket.items.each do |it|
          item_discount( it , discount )
        end
      end
      @basket.save!
    else
      flash[:error] = "No discount given"
    end
    redirect_to edit_basket_path(@basket)
  end

  # ean search at the top of basket edit
  def ean
    return if redirect_if_locked
    ean = params[:ean]
    ean.sub!("P+" , "P-") if ean[0,2] == "P+"
    if( ean.length == 13 and ean.to_i > 10000 )
      prod = Product.find_by_ean ean
    else
      prod = Product.find_by_name ean
    end
    if(prod)
      @basket.add_product prod
      redirect_to edit_basket_path(@basket)
    else
      redirect_to products_path(:q => {"name_cont"=> ean}, :basket => @basket.id)
    end
  end

  def edit
    return if redirect_if_locked
    if p_id = (params[:add] || params[:remove])
      add = params[:add].blank? ? -1 : 1
      @basket.add_product Product.find(p_id) , add
      flash.now.notice = params[:add] ? t('product_added') : t('item_removed')
    elsif prod_id = params[:delete]
      @basket.remove_product Product.find(prod_id)
      flash.now.notice = t('item_removed')
    end
    @basket.save!
  end

  def create
    @basket = Basket.create(params_for_basket)
    if @basket.save
      redirect_to basket_path(@basket), :notice => t(:create_success, :model => "basket")
    else
      render :edit
    end
  end

  def update
    return if redirect_if_locked
    respond_to do |format|
      if @basket.update_attributes(params_for_basket)
        format.html do
          flash.notice = t(:update_success, :model => "basket")
          redirect_to edit_basket_path(@basket)
        end
        format.json { render( partial: "baskets/basket.json" , status: :ok) }
      else
        format.html { render :edit }
        format.json { render json: {}, status: :error }
      end
    end
  end

  def destroy
    # the idea is that you can't delete a basket once something has been "done" with it (order..)
    if @basket.locked?
      flash.notice = t('basket_locked')
    else
      flash.notice = t('basket') + " " + t(:deleted)
      @basket.destroy
    end
    redirect_to baskets_path
  end

  private

  # check if the @basket is locked (no edits allowed)
  # and if so redirect to show
  # return if redirect happened
  def redirect_if_locked
    if @basket.locked?
      flash.notice = t('basket_locked')
      redirect_to basket_path(@basket)
      return true
    end
    return false
  end

  def item_discount item , discount
    item.price = (item.product.price * ( 1.0 - discount.to_f/100.0 )).round(2)
    item.save!
  end

  def load_basket
    @basket = Basket.find(params[:id])
    session[:basket] = nil # used to change links on product page, null when we come back
  end

  def params_for_basket
    return {} if params[:basket].blank? or params[:basket].empty?
    params.require(:basket).permit( :items_attributes => [:quantity ,:name, :price , :id, :product_id] )
  end
end

app/helpers/baskets_helper.rb
# encoding : utf-8
require "admin_helper"
module BasketsHelper
  def has_receipt?
    styles = RubyClerks.config(:print_styles)
    return false if styles.nil?
    return styles.split.include?("receipt")
  end
  def basket_edit_link basket , options = {}
    return "---" unless basket
    if basket.locked?
      text =  I18n.t(:locked) + ": "
      case basket.kori
      when Order
        text += I18n.t(:order)
        link = order_path(basket.kori)
      when Purchase
        text += I18n.t(:purchase)
        link = purchase_path(basket.kori)
      else
        raise "System Error: Locked basket without order #{basket.id}"
      end
    else
      if basket.kori
        key = basket.kori.class.name.downcase
        text = I18n.t(key)
      else
        text = t(:basket)
      end
      if(basket.kind)
        text = basket.name || t(:new)
        link = edit_house_path(basket)
      else
        link = edit_basket_path(basket)
      end
    end
    return link_to text , link , options
  end
end

app/views/baskets/_small.html.haml
.col-md-12
  %table.table.table-striped.table-sm
    %thead
      %tr
        %th= t(:scode)
        %th= t(:name)
        %th= t(:quantity)
        %th= t(:price)
    %tbody
      - basket.items.each do |item|
        %tr{:class => "line-#{cycle("1","2")}"}
          %td= item.product.scode if item.product
          %td.name= link_to_if item.product, item.name , product_path(item.product)
          %td= item.quantity
          %td= euros item.price
      %tr
        %td{:colspan => 2}
          = basket_edit_link @basket , :class => "btn btn-primary"
        %td
          = t(:quantity)
          = basket.quantity
        %td
          = t(:total)
          = euros basket.total_price
      = yield :basket

app/views/baskets/edit.html.haml
.row.basket_edit_start
  .col-md-12
  %h2
    = t(:edit) + ": "
    -if @basket.kori_type
      = t(@basket.kori_type.downcase)
    = "(#{@basket.id})"

.row
  .col-md-8.ean_form
    = form_tag( ean_basket_path(@basket ), class: "form-inline" , id: "auto_form" )  do |f|
      = text_field_tag  :ean , "" , :autofocus => true ,  placeholder: t(:add_to_basket)  ,
                        :class => "ean_field form-control" , :size => 45 , id: "auto_ean"
      = submit_tag t(:search) ,  :class => "btn btn-xs btn-info ean_submit"
  .col-md-3
    = t(:discount )
    = form_tag edit_basket_path(@basket) , :method => :get do
      = select_tag("discount" , options_for_select( ["",0,5,10,15,20,25,30,35,40,50,60,70] ),
                    :onchange => "window.location.href='#{discount_basket_path(@basket)}?discount=' + this.value" ,
                    class: "form-control")
:coffee
  $ ->
    $('#auto_ean').autocomplete(
      minLength: 2
      source: '#{names_products_path(:json)}'
      focus: (event, ui) ->
        $('#auto_ean').val ui.item.name
        false
      select: (event, ui) ->
        $('#auto_ean').val ui.item.ean
        $('#auto_form').submit()
        false
    ).data('uiAutocomplete')._renderItem = (ul, item) ->
      $('<li></li>').data('ui-autocomplete-item', item).append('<a>' + item.name + '</a>').appendTo ul
    return


= form_for(@basket) do |f|
  .row
    .col-md-12
      %table.table.table-hover.table-sm
        %thead
          %tr
            %th= t(:name)
            %th= t(:quantity)
            %th= t(:price)
            %th= t(:discount)
            %th{:colspan => "3"}= t(:actions)
        %tbody
          - @basket.items.each do |item|
            %tr{:class => "line-#{cycle("1","2")}"}
              %td.name= item.name
              = f.fields_for :items , item do |iform|
                %td= iform.text_field :quantity , :label => false
                %td= iform.text_field :price , :label => false
              %td
                = select_tag("discount" , options_for_select( [item.discount,0,5,10,15,20,25,30,35,40,50,60,70] ), :onchange => "window.location.href='#{discount_basket_path(@basket)}?item=#{item.id}&discount=' + this.value"  )
              %td
                = link_to t(:delete) , edit_basket_path(:delete => item.product.id)
                = link_to t(:remove) , edit_basket_path(:remove => item.product.id)
                = link_to t(:more) , edit_basket_path(:add => item.product.id)

          %tr
            %td{:colspan => 4}
              = f.submit :class => "btn btn-success commit"
            %td.count
              = t(:count)
              = @basket.items.length
            %td.total
              = t(:total)
              = euros @basket.total_price


    .col-12
      .row.form-actions
        .col-md-2
          = link_to  t(:new) + ' ' + t(:basket) , new_basket_path , :class => "btn btn-primary"
        - if @basket.kori_type.blank? and not @basket.empty?
          .col-md-2
            = link_to t(:make_order), order_basket_path(@basket), :class => "btn btn-primary make_order"
          .col-md-2
            = link_to t(:make_purchase), purchase_basket_path(@basket), :class => "btn btn-primary make_purchase"
        - elsif @basket.isa(:order)
          .col-md-2
            = link_to t(:to_order), order_path(@basket.kori), :class => "btn btn-primary to_order"
          - if has_receipt?
            .col-md-2
              = link_to t("receipt.header"), receipt_order_path(@basket.kori), :class => "btn btn-primary print_order"
        - elsif @basket.isa(:purchase)
          .col-md-2
            = link_to t(:to_purchase), purchase_path(@basket.kori), :class => "btn btn-primary to_purchase"
        -if @basket.length
          .col-md-2
            = link_to t(:house) , edit_house_path(@basket) , :class => "btn btn-primary"
        -unless @basket.locked? or @basket.kori
          .col-md-2
            = link_to t(:destroy) , basket_path(@basket), :confirm => t(:are_you_sure ), :method => :delete, :title => t(:destroy) , :class => "btn btn-danger"
        -unless @basket.locked?
          .col-md-2
            = link_to t(:nolla) , zero_basket_path(@basket), :class => "btn btn-danger"

.basket_edit_end

app/views/baskets/index.html.haml
.row.basket_index_start
  .col-md-9.baskets
    .row
      .col-md-10
        %h2= t(:baskets)
        = paginate @baskets
      .col-md-2
        = link_to  t(:new) + ' ' + t(:basket) , new_basket_path , :class => "btn btn-primary"
  .col-md-3
    = image_tag "ruby_clerks/baskets.jpg" , :class => "img-responsive"
.row
  .col-md-9
    %div
      %table.table.table-striped.table-bordered.table-sm
        %thead
          %tr
            %th= sort_link [:office,@q], :created_at
            %th= sort_link [:office,@q], :total_price
            %th= t(:items)
            %th
              %label.checkbox
                = @basket_scope.length.to_s + " " + t("baskets")
        %tbody
          - @baskets.each do |basket|
            %tr{:class => "line-#{cycle("1","2")}"}
              %td
                = date(basket.created_at.to_date)
              %td
                = euros basket.total_price
              %td
                - basket.items.each do |item| #should break at 5 and do the rest as tooltip
                  = item.quantity
                  x
                  = item.name
                  %br
              %td= basket_edit_link(basket)
    = paginate @baskets
  .col-md-3
    = search_form_for @q , :html => { :class => "form-horizontal" }, :method => :get do |f|
      .form-group.row
        .col-md-3
          = f.label(:type)
        .col-md-9
          = f.select :kori_type_eq, [["",""] , [t(:order) , "Order"] , [t(:purchase),"Purchase"]] , {},  :class => "form-control"
      .form-group
        = f.text_field :items_name_cont , :class => "form-control" , :placeholder => t(:product) + " " +t(:name_contains)
      .form-group.row
        .col-md-4
          = f.label(:total_price)
        .col-md-4
          = f.text_field :total_price_gt , :class => "form-control"
        .col-md-4
          = f.text_field :total_price_lt , :class => "form-control"
      .form-group.row
        .col-md-4
          = f.label(:created_at)
        .col-md-4
          = f.search_field :created_at_gteq , :class => "form-control datepicker" , :value => sort_date(:created_at_gteq)
        .col-md-4
          = f.search_field :created_at_lteq , :class => "form-control datepicker" , :value => sort_date(:created_at_lteq)
      = f.submit t(:filter), :class => "btn btn-success"
      = link_to  t(:cancel), baskets_path, :class => "btn btn-warning"
.basket_index_end

app/views/baskets/show.html.haml
%h2.basket_show_start
  = t(:basket) + " : "
  = t(:order) + " " + @basket.kori.id_number if @basket.isa(:order)
.col-md-4
  %p
    %b
      = t(:total_price) + " : " +  euros(@basket.total_price)
.col-md-4
  %p
    %b
      = t(:total_tax) + " : " + euros(@basket.total_tax)

= render "small" , :basket => @basket

.col-md-12.basket_show_end
  = link_to t(:back), orders_path, :class => "btn btn-warning"
  = link_to t(:destroy) , basket_path(@basket), :data => { :confirm => t(:are_you_sure) }, :method => :delete, :title => t(:destroy) , :class => "btn btn-danger" unless @basket.locked.blank? or @basket.kori
  = link_to t("receipt.header"), receipt_order_path(@basket.kori) , :target => "_blank" , :class => "btn btn-primary print_order" if @basket.isa(:order)