config/routes.rb
Rails.application.routes.draw do

  root to: 'high_voltage/pages#show' , id: 'index'

  get "/blog" , to: "blog#index" , as: :blog_index
  get "/blog/*title" , to: "blog#post" , as: :blog_post

  get "sign_out" => "sessions#sign_out"
  get "sign_in"  => "sessions#sign_in"
  post "create_session"  => "sessions#create"
  match "sign_up" => "sessions#sign_up" , :via => [:get ,:post]

  resources :purchases do
    collection do
      get "search" => "purchases#index"
    end
    member do
      get :invoice, to: 'purchase_invoices#show'
      get :order
      get :receive
      get :inventory
    end
  end

  resources :baskets do
    collection do
      get "search" => "baskets#index"
    end
    member do
      get :discount
      post :ean
      get :order
      get :purchase
      get :zero
    end
  end

  resources :houses , :except => [:show , :destroy] do
    collection do
      get :products
    end
  end

  resources :orders , :except => [:edit] do
    collection do
      get "search" => "orders#index"
    end
    member do
      get "mail/:act" , :action => :mail , :as => :mail
      get :pay
      get :shipment
      get :ship
      get :deduct_only
      get :cancel
      patch :shipment
      get :invoice
      get :receipt
      get :slip
      get :reminder
      get :rakennus
      get :ecoframe
      get "finvoice_:num" , action: :finvoice , as: :finvoice
    end
  end

  resources :items do
    collection do
      get "search" => "items#index"
    end
    member do
    end
  end

  resources :categories do
    collection do
      get "search" => "categories#index"
    end
    member do
    end
  end

  resources :products do
    collection do
      get "search" => "products#index"
      get :names
    end
    member do
      get :delete
      get :barcode  #print the barcode and price on a 50x25 mm area
    end
  end

  resources :clerks do
    collection do
      get "search" => "clerks#index"
    end
    member do
    end
  end

  resources :addresses do
    collection do
      get "search" => "addresses#index"
    end
  end

  resources :suppliers do
    collection do
      get "search" => "suppliers#index"
    end
    member do
    end
  end

  get "manage/all" => "manage#all"
  get '/manage/reports' => 'manage#reports'

  get "api/purchase" => "api#purchase" , format: :json

  get "/3d/*id" => 'kolme_d#show' , as: :kolme_d
end

Rails.application.config.after_initialize do |application|
  application.routes.append do
    match '*path', via: :all, to: 'high_voltage/pages#show' , id: "404"#if Rails.production?
  end
end

app/controllers/purchases_controller.rb
# encoding : utf-8
class PurchasesController < AdminController

  before_action :load_purchase, :only => [:show, :edit, :update , :order , :receive , :inventory,:destroy]

  # Uncomment for check abilities with CanCan
  #authorize_resource

  def index
    @q = Purchase.ransack params[:q]
    @purchase_scope = @q.result(:distinct => true)
    @purchases = @purchase_scope.includes(:basket => {:items => :product} ).page( params[:page])
  end

  def show
  end

  # order this from supplier
  def order
    @purchase.order!
    redirect_to purchase_path(@purchase), :notice => t(:ordered)
  end

  # receive the stuff (ie add to inventory)
  def receive
    items = @purchase.receive!
    redirect_to purchase_path(@purchase), :notice => [t(:received) ,items ,t(:items)].join(" ")
  end

  # receive the stuff (ie add to inventory)
  def inventory
    items = @purchase.inventory!
    flash.notice = [t(:inventorized) ,items ,t(:items)].join(" ")
    redirect_to purchase_path(@purchase)
  end

  def new
    today = Date.today
    basket = Basket.create!
    @purchase = Purchase.new :name => "#{I18n.t(:purchase)} #{I18n.l(today)}" , :basket => basket
    if( supplier_id = params[:supplier])
      @purchase.supplier = Supplier.find( supplier_id )
    end
    @purchase.save!
    redirect_to edit_basket_path basket
  end

  def edit
    if( @purchase.basket.locked?)
      redirect_to purchase_path(@purchase) , notice: "Cant edit, locked"
    end
    create_data
  end

  def update
    respond_to do |format|
      if @purchase.update_attributes(params_for_model)
        format.html { redirect_to purchase_path(@purchase), :notice => t(:update_success, :model => "purchase") }
        format.json { respond_with_bip(@purchase) }
      else
        format.html { render :action => :show }
        format.json { respond_with_bip(@purchase) }
      end
    end
  end

  def destroy
    # the idea is that you can't delete a basket once something has been "done" with it (order..)
    if @purchase.basket.locked?
      flash.notice = t('basket_locked')
    else
      flash.notice = t('purchase') + " " + t(:deleted)
      @purchase.basket.destroy
      @purchase.destroy
    end
    redirect_to purchases_path
  end

  protected
  def create_data
    @products = Product.where(supplier_id: @purchase.supplier_id).
                        where("stock_level > ?", 0).
                        includes(:category)
    @ordered_products = Hash.new(0)
    @orders =  Order.where("created_at > ?" ,Time.now - 8.weeks).where(shipped_on: nil)
    @orders.includes(basket: {items: :product}).each do |order|
      order.basket.items.each{ |item| @ordered_products[item.product_id] += item.quantity}
    end
    @basket = @purchase.basket
  end

  def load_purchase
    @purchase = Purchase.where( :id => params[:id]).includes( :basket => {:items => {:product => :supplier}} ).first
  end

  private

  def params_for_model
    params.require(:purchase).permit(:name,:ordered_on,:received_on,:basket_id)
  end
end

app/helpers/purchases_helper.rb
# encoding : utf-8
require "admin_helper"
module PurchasesHelper
end

app/views/purchases/_orders.html.haml
%table.table.table-striped.table-sm
  %thead
    %tr
      %th= t("order_number")
      %th= t(:name)
      %th= t(:ordered_on)
      %th= t(:quantity)
      %th= t(:total)
  %tbody
    - @orders.each do |order|
      %tr{:class => "line-#{cycle("1","2")}"}
        %td
          = link_to order.id , order
        %td
          = link_to order, class: :poppy do
            = order.name
            .overlay
              = render "baskets/small" , basket: order.basket
        %td= date(order.ordered_on)
        %td.quantity
          = order.basket.items.length
        %td
          = order.basket.total_price

app/views/purchases/edit.html.haml
.row.purchase-app
  .col-md-6.purchases
    %h2= in_place @purchase , :name
  .col-md-2.pill{ "v-bind:class" => "{active_pill: tab == 1}"}
    %h6
      %a{"@click" => "tab = 1"}= t(:basket)
  .col-md-2.pill{"v-bind:class" => "{active_pill: tab == 2}"}
    %h6
      %a{"@click" => "tab = 2"}= t(:products)
      \&nbsp;
      %a.right{"@click" => "products_to_basket"}
        =image_tag "plus.png" , width: "20px"
  .col-md-2.pill{"v-bind:class" => "{active_pill: tab == 3}"}
    %h6
      %a{"@click" => "tab = 3"}=t(:orders)
      \&nbsp;
      %a.right{"@click" => "orders_to_basket"}
        =image_tag "plus.png" , width: "20px"

  .col-md-12.tab.basket{"v-bind:class" => "{active_tab: tab == 1}"}
    %table-component{ ":columns": "basket_columns" ,
                      ":table_data": "basket.items",
                      ":column_order": "basket_order"}
      %template{ slot: "name" , "slot-scope" => "row"}
        %a{ ":href" => "'/products/' + row.object.product_id"}
          {{row.object.name}}
      %template{ slot: "quantity" , "slot-scope" => "row" , ":class": "quantity"}
        {{row.object.quantity}}
        .overlay
          %a{ "@click" => "row.object.quantity += 1; changed = true"}
            =image_tag "plus.png"
          \&nbsp;
          %span {{row.object.quantity}}
          \&nbsp;
          %a{ "@click" => "row.object.quantity -= 1; changed = true"}
            =image_tag "minus.png"
      %template{ slot: "total" , "slot-scope" => "row"}
        {{(row.object.price * row.object.quantity).toFixed(2)}}
      %template{slot: "last"}
        %th= t(:total)
        %td
        %td
        %td
          {{total_amount()}}
        %td
        %td
          = form_for(@purchase.basket) do |f|
            %span{"v-for" => "(item , index) in this.basket.items"}
              %input{hidden: true , "v-bind" => "itemProp(item,index,'id')" , "v-if"=> "item.id"}/
              %input{hidden: true , "v-bind" => "itemProp(item,index,'name')"}/
              %input{hidden: true , "v-bind" => "itemProp(item,index,'price')"}/
              %input{hidden: true , "v-bind" => "itemProp(item,index,'quantity')"}/
              %input{hidden: true , "v-bind" => "itemProp(item,index,'product_id')"}/
            = f.submit :class => "btn btn-success commit" ,"v-if" => "changed", "@click" => "submit_basket"
        %th
          {{(total_price()/ 1.24).toFixed(2)}}

  .col-md-12.tab{"v-bind:class" => "{active_tab: tab == 2}"}
    %table-component{ ":columns": "product_columns" ,
                      ":table_data": "products",
                      ":column_order": "product_order"}
      %template{ slot: "name" , "slot-scope" => "row"}
        %a{ ":href" => "'/products/' + row.object.id"}
          {{row.object.name}}
      %template{ slot: "add" , "slot-scope" => "row"}
        %a{ "@click" => "to_basket(row.object)" , "v-if" => "!in_basket(row.object)"}
          =image_tag "plus.png" , width: "30px"

  .col-md-12.tab{"v-bind:class" => "{active_tab: tab == 3}"}
    =render "orders"
.row
  .col-md-2
    = link_to( t(:back) , purchase_path(@purchase) , class: "btn btn-info")
  .col-md-2
    = link_to t(:edit) + " " + t(:basket), edit_basket_path(@purchase.basket), :class => "btn btn-info edit_basket" unless @purchase.basket.locked?
  .col-md-2
    = link_to t(:destroy) , purchase_path(@purchase), :data => { :confirm => t(:are_you_sure) }, :method => :delete, :title => t(:destroy) , :class => "btn btn-danger" unless @purchase.basket.locked?

=render "components/table"

:ruby2js
  class App < Vue
    options el: '.purchase-app'
    def initialize
      @purchase = #{@purchase.to_json(include: :supplier).html_safe}
      @tab = 1
      @changed = false
      @basket = #{ render( partial: "baskets/basket.json").html_safe }
      @basket_columns = { position: {name: "#{t(:position)}"},
                          scode: {name: "#{t(:scode)}"},
                          name: {name: "#{t(:name)}" , searchable: true },
                          quantity: {name: "#{t(:quantity)}"},
                          pack_unit: {name: "#{t(:pack_unit)}"},
                          price: {name: "#{t(:price)}"},
                          total: {name: "#{t(:total)}" , sortable: false} }
      @basket_order = [:position,:scode,:name,:quantity,:pack_unit,:price,:total]
      @products = #{ render( partial: "purchases/products.json").html_safe }
      @product_order = [ :scode , :name , :category , :inventory , :stock_level ,
                         :stock_diff , :pack_unit , :cost , :ordered , :add]
      @product_columns = {scode:      {name: "#{t(:scode)}" },
                          name:       {name: "#{t(:name)}" , searchable: true},
                          category:   {name: "#{t(:category)}" , searchable: true},
                          inventory:  {name: "#{t(:inventory)}" },
                          stock_level:{name: "#{t(:stock_level).split.first}"} ,
                          stock_diff: {name: "Diff"},
                          pack_unit:  {name: "#{t(:pack_unit)}"},
                          cost:       {name: "#{t(:cost)}"} ,
                          ordered:    {name: "#{t(:order)}"} ,
                          add:        {name: ""} }
    end
    def itemProp(item, index , prop)
      return { value: item[prop] ,
              name: 'basket[items_attributes][' + index +'][' + prop + ']',
              id: 'basket_items_attributes_' + index + '_' + prop
             }
    end
    def submit_basket(event)
      event.preventDefault()
      jQuery.post( '/baskets/' + @basket.id , jQuery(".edit_basket").serializeArray() , null , "json").
        done() { |saved_basket| @basket = saved_basket ; @changed = false }.
        fail() { console.log( "error" ) }
    end
    def orders_to_basket(_)
      @products.each { |product| self.to_basket(product) if(product.ordered) }
    end
    def products_to_basket(_)
      @products.each() {|product| self.to_basket(product) }
    end
    def to_basket(product)
      amount = product.ordered + product.stock_level - product.inventory
      return if(amount < 0)
      if(product.pack_unit > 1)
        amount = Math.ceil(amount / product.pack_unit ) * product.pack_unit
      end
      item = this.in_basket(product)
      if(item)
        @changed = true if( item.quantity != amount)
        item.quantity = amount
      else
        this.basket.items.push({ name: product.name ,
                             quantity: amount,
                                scode: product.scode,
                                price: product.cost,
                           product_id: product.id,
                            pack_unit: product.pack_unit,
                             position: product.position});
        @changed = true
      end
    end
    def in_basket(product)
      return @basket.items.find { |item| item.product_id == product.id }
    end
    def total_price(_)
      sum = 0
      @basket.items.each { |item| sum += item.price * item.quantity }
      return sum
    end
    def total_amount(_)
      sum = 0
      @basket.items.each { |item| sum += item.quantity }
      return sum
    end
  end

app/views/purchases/index.html.haml
.row.purchase_index_start
  .col-md-9.purchases
    .row
      .col-md-10
        %h2= t(:purchases)
        = paginate @purchases
      .col-md-2
        = link_to  t(:new) + ' ' + t(:purchase) , new_purchase_path , :class => "btn btn-primary new_purchase"
  .col-md-3
    = image_tag "ruby_clerks/purchases.jpg" , :class => "img-responsive"
.row
  .col-md-9
    %div
      %table.table.table-striped.table-sm
        %thead
          %tr
            %th= t(:name)
            %th= sort_link [:office,@q], :ordered_on
            %th= sort_link [:office,@q], :received_on
            %th= t(:items)
            %th= sort_link [:office,@q], :basket_total_price
            %th= @purchase_scope.length.to_s + " " +  t(:purchases)
        %tbody
          - @purchases.each do |purchase|
            %tr{:class => "line-#{cycle("1","2")}"}
              %td= purchase.name
              %td= date(purchase.ordered_on)
              %td= date(purchase.received_on)
              %td= purchase.basket.items.length
              %td= link_to euros(purchase.basket.total_price) , basket_path(purchase.basket)
              %td
                -if purchase.basket.locked?
                  = link_to t(:show) , purchase_path(purchase), :title => t(:show)
                -else
                  = link_to t(:edit) , edit_purchase_path(purchase), :title => t(:edit)
      .btn-toolbar
        .btn-group
          = paginate @purchases
  .col-md-3
    = search_form_for @q, :html => { :class => "form-horizontal" }, :method => :get do |f|
      .form-group
        = f.text_field :name_cont , :class => "form-control" , :placeholder =>  t(:name)
      .row
        .col-md-10
          = f.label(:ordered_on)
      .row
        .col-md-5
          = f.text_field :ordered_on_gteq , :class => "form-control datepicker"
        .col-md-5
          = f.text_field :ordered_on_lteq , :class => "form-control datepicker"
      .row
        .col-md-10
          = f.label(:received_on)
      .row
        .col-md-5
          = f.text_field :received_on_gt , :class => "form-control datepicker"
        .col-md-5
          = f.text_field :received_on_lt , :class => "form-control datepicker"
      %br
      = f.submit t(:filter),  :id => :filter , :class => "btn btn-success"
      = link_to  t(:cancel), purchases_path, :class => "btn btn-warning"
.purchase_index_end

app/views/purchases/show.html.haml
.row.purchase_show_start
  .col-md-6
    %h2
      = t(:purchase)
    %p
      %b= t(:name)
      = in_place @purchase , :name
  .col-md-4
    - @purchase.basket.suppliers.each do |s|
      = link_to( t(:new) + " : " + s.supplier_name , new_purchase_path(supplier: s.id) ,:class => "btn btn-primary purchase_link")
  .col-md-1
    -unless @purchase.received_on
      = link_to t(:inventory) , inventory_purchase_path(@purchase) , :class => "btn btn-primary btn-danger inventory_link", :data => { :confirm => t(:are_you_sure) }

.row
  .col-md-3
    %p
      %b
        = t(:ordered_on) + " : "
        -if @purchase.ordered_on
          = date(@purchase.ordered_on)
        -else
          = link_to t(:order) , order_purchase_path(@purchase) , :class => "btn btn-primary order_link"
  .col-md-3
    %p
      %b
        = t(:received_on) + " : "
        -if @purchase.received_on
          = date(@purchase.received_on)
        -else
          = link_to t(:receive) , receive_purchase_path(@purchase) , :class => "btn btn-primary receive_link"
  .col-md-6
    %p
      %b
        = t(:suppliers) + " : "
      - @purchase.basket.suppliers.each do |s|
        = link_to( s.supplier_name , supplier_path(s))

= render "baskets/small" , :basket => @purchase.basket

.row
  .col-md-2
    = link_to t(:edit) + " " + t(:purchase), edit_purchase_path(@purchase), :class => "btn btn-success edit_basket" unless @purchase.basket.locked?
  .col-md-2
    = link_to t(:edit) + " " + t(:basket), edit_basket_path(@purchase.basket), :class => "btn btn-info edit_basket" unless @purchase.basket.locked?
  .col-md-2
    = link_to t(:back), purchases_path, :class => "btn btn-warning"
  .col-md-2
    = link_to "Print Invoice" , "/purchases/#{@purchase.id}/invoice" , class: "btn btn-primary"
  .col-md-2
    = link_to t(:edit) , edit_purchase_path(@purchase), :class => "btn btn-info edit_basket" unless @purchase.basket.locked?
  .col-md-2
    = link_to t(:destroy) , purchase_path(@purchase), :data => { :confirm => t(:are_you_sure) }, :method => :delete, :title => t(:destroy) , :class => "btn btn-danger" unless @purchase.basket.locked?