config/routes.rb
Rails.application.routes.draw do

  root to: 'high_voltage/pages#show' , id: 'index'

  get "/blog" , to: "blog#index" , as: :blog_index
  get "/blog/*title" , to: "blog#post" , as: :blog_post

  get "sign_out" => "sessions#sign_out"
  get "sign_in"  => "sessions#sign_in"
  post "create_session"  => "sessions#create"
  match "sign_up" => "sessions#sign_up" , :via => [:get ,:post]

  resources :purchases do
    collection do
      get "search" => "purchases#index"
    end
    member do
      get :invoice, to: 'purchase_invoices#show'
      get :order
      get :receive
      get :inventory
    end
  end

  resources :baskets do
    collection do
      get "search" => "baskets#index"
    end
    member do
      get :discount
      post :ean
      get :order
      get :purchase
      get :zero
    end
  end

  resources :houses , :except => [:show , :destroy] do
    collection do
      get :products
    end
  end

  resources :orders , :except => [:edit] do
    collection do
      get "search" => "orders#index"
    end
    member do
      get "mail/:act" , :action => :mail , :as => :mail
      get :pay
      get :shipment
      get :ship
      get :deduct_only
      get :cancel
      patch :shipment
      get :invoice
      get :receipt
      get :slip
      get :reminder
      get :rakennus
      get :ecoframe
      get "finvoice_:num" , action: :finvoice , as: :finvoice
    end
  end

  resources :items do
    collection do
      get "search" => "items#index"
    end
    member do
    end
  end

  resources :categories do
    collection do
      get "search" => "categories#index"
    end
    member do
    end
  end

  resources :products do
    collection do
      get "search" => "products#index"
      get :names
    end
    member do
      get :delete
      get :barcode  #print the barcode and price on a 50x25 mm area
    end
  end

  resources :clerks do
    collection do
      get "search" => "clerks#index"
    end
    member do
    end
  end

  resources :addresses do
    collection do
      get "search" => "addresses#index"
    end
  end

  resources :suppliers do
    collection do
      get "search" => "suppliers#index"
    end
    member do
    end
  end

  get "manage/all" => "manage#all"
  get '/manage/reports' => 'manage#reports'

  get "api/purchase" => "api#purchase" , format: :json

  get "/3d/*id" => 'kolme_d#show' , as: :kolme_d
end

Rails.application.config.after_initialize do |application|
  application.routes.append do
    match '*path', via: :all, to: 'high_voltage/pages#show' , id: "404"#if Rails.production?
  end
end

app/models/product.rb
# RubyClerk product may represent one of three things
# - the normal product (all attributes work as expected)
# attributes : see permitted_attributes + inventory + deleted_on

class Product < ActiveRecord::Base
  has_many :items

  belongs_to :category , optional: true
  belongs_to :supplier , optional: true

  # default product scope only lists non-deleted products
  default_scope {where(:deleted_on => nil).order(created_at: :desc) }
  scope :with_inventory, -> { where("inventory > 0") }

  validates :price, :numericality => true
  validates :cost, :numericality => true
  validates :name, :presence => true
  validates :deleted_on , :absence => true , :if => :has_inventory?

  before_save :fix_cost

  def has_inventory?
    self.inventory > 0
  end

  # has the product been deleted (marked as deleted)
  def deleted?
    not deleted_on.blank?
  end

  # deleting sets the deleted_on flag to today
  # Products can not be deleted because of the risk of invalidating old orders
  # to actually remove a product from the db, use the console
  def delete
    self.deleted_on = Date.today
    self
  end

  def category_name
    self.category_id ? self.category.name : ""
  end

  def copy_product
    Product.new :tax => self.tax , :weight => self.weight , :cost => self.cost ,
        :supplier_id => self.supplier_id , :category_id => self.category_id ,
        :price => self.price , :name => self.name + " copy",
        description: self.description , summary: self.summary,
        phase: self.phase , dimension: self.dimension
  end

  def update_price(save) #boolean
    return 0 if summary.count(":") < 2
    puts "#{self.id} #{summary}"
    lines = summary.split("\n")
    total = 0
    lines.each do |line|
      parts = line.split(":")
      unless parts.length == 3
        puts "INVALID data #{line}"
        next
      end
      prod = Product.find(parts[1])
      total += prod.price * parts[2].to_f
    end
    if(save)
      update_attribute(:price, total)
    else
      self.price = total
    end
    puts "updating #{self.name} to #{total}"
    return 1
  end

  private
  def fix_cost
    if self.cost == 0.0
      self.cost = self.price / 2
    end
  end
end

app/controllers/products_controller.rb
# encoding : utf-8

class ProductsController < AdminController
  include ProductsHelper
  helper ProductsHelper

  include Barcode

  before_action :load_product, :only => [:show, :edit, :update, :destroy ]

  # Uncomment for check abilities with CanCan
  #authorize_resource

  def index
    param = params[:q] || {}
    @q = Product.ransack( param )
    @product_scope = @q.result(:distinct => true).includes( :supplier , :category)
    @products = @product_scope.page(params[:page])
    create_used_inventory_list if( available_inventory )
  end

  def names
    @products = Product.where('name ilike ?', "%#{params[:term]}%").limit(20)
    render layout: false
  end

  def show
  end

  def new
    if(copy = params[:copy])
      @product = Product.find(copy).copy_product
    else
      @product = Product.new :tax => RubyClerks.config("defaults.tax")
    end
    render :edit
  end

  def edit
  end

  def create
    @product = Product.create(params_for_model)
    @product.update_price(false)
    if @product.save
      flash.notice = t(:create_success, :model => "product")
      redirect_to product_path(@product)
    else
      flash.alert = t(:fix_errors, :model => "product")
      render :action => :edit
    end
  end

  def update
    @product.assign_attributes(params_for_model)
    @product.update_price(false)
    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => t(:update_success, :model => "product")) }
        format.json { respond_with_bip(@product) }
      else
        format.html { render :action => :edit }
        format.json { respond_with_bip(@product) }
      end
    end
  end

  def destroy
    @product.delete
    if @product.save
      redirect_to products_url , :notice => t("deleted") + ": " + @product.name
    else
      redirect_to product_url(@product) , :notice => "#{t(:error)} : #{t(:product_has_inventory)}"
    end
  end

  private

  def create_used_inventory_list
    order_ids = Order.where("created_at > ?" , 1.month.ago ).pluck(:id)
    basket_ids = Basket.where(kori_id: order_ids).where(locked: nil).pluck(:id)
    @product_inventory = Hash.new(0)
    for_products = available_inventory ? @product_scope : @products
    product_ids = for_products.each {|p| p.id }
    Item.where(basket_id: basket_ids).where(product_id: product_ids).each do |item|
      @product_inventory[item.product_id] = @product_inventory[item.product_id] + item.quantity
    end
  end

  def load_product
    @product = Product.find(params[:id])
  end

  def params_for_model
    params.require(:product).permit(:price,:cost,:weight,:name,:description, :summary,
                                    :stock_level,:ean,:tax,:properties,:scode,
                                    :category_id,:supplier_id, :position, :pack_unit,
                                    :dimension , :phase)
  end
end

app/helpers/products_helper.rb
# encoding : utf-8

module ProductsHelper

  # show inventory that is really available, ie has not been "reserved" by unshipped orders
  def available_inventory
    params[:in_orders]
  end
end

app/views/products/_preview_box.haml
.admin
  .product-container
    %h4.product-name
      =product.name
    .row
      .col-md-4
      .col-md-8
        .product-fact
          %p= markdown product.summary
    .row
      .product-list-price
        = euros product.price

app/views/products/_triple.html.haml
.row
  %h3= products.length.to_s + " " + t(:products)
  %table.table.table-striped.table-bordered.table-sm
    %tbody
      - products.in_groups_of(3).each do |array|
        %tr{:class => "line-#{cycle("1","2")}"}
          -array.each do |product|
            -next unless product
            %td
              = link_to product_path(product), :title => t(:show) do
                = product.name

app/views/products/edit.html.haml
.row
  .h4
    = t(:edit) + ":"
    = @product.name

= simple_form_for(@product ) do |f|
  .product_edit_start.row
    .col-md-6
      = f.input :name
    .col-md-3
      = f.input :price
    .col-md-3
      = f.input :cost

    .col-md-3
      = f.input :ean
    .col-md-3
      = f.input :scode
    .col-md-3
      = f.input :weight
    .col-md-3
      = f.input :tax
    .col-md-3
      = f.input :phase
    .col-md-3
      = f.input :dimension
    .col-md-3
      = f.input :pack_unit
    .col-md-3
      = f.input :position

    .col-md-6
      = f.association :supplier , label_method: :supplier_name,
                                  value_method: :id, include_blank: true
    .col-md-6
      = f.association :category , label_method: :name,
                                  value_method: :id, include_blank: true

    .col-md-6
      = f.input :summary,  input_html: {rows: 4}
    .col-md-6
      = f.input :description, input_html: {rows: 10}

    .col-md-4
      = f.submit :class => "btn btn-success"
    .col-md-4
      - url = @product.persisted? ? product_path(@product) : products_path
      = link_to t(:cancel), url, :class => "btn btn-warning"

.product_edit_end

app/views/products/index.csv.erb
<%= [t(:position), t(:name) , t(:inventory) , t(:category) , t(:price)].join(";") %>
<% @product_scope.each do |product| %>
  <% values = [product.position] %>
  <% values << product.name %>
  <% values <<  product.inventory  %>
  <% if(available_inventory) %>
   <% values << (available_inventory  ? "#{product.inventory - @product_inventory[product.id]} / #{@product_inventory[product.id]} "
    : product.inventory ) %>
  <% end %>
  <% values << product.category_name %>
  <% values << product.price %>
  <%= values.join(";")   %>
<%end%>

app/views/products/index.html.haml
.row.product_index_start
  .col-md-9.products
    .row
      .col-md-10
        %h2
          - if params[:basket]
            %br
            %br
            %br
            = t(:choose_product_for_basket)
          -else
            = t(:products)
        = paginate @products
      .col-md-2
        = link_to  t(:new) + ' ' + t(:product) , new_product_path , :class => "btn btn-primary"
  .col-md-3
    = image_tag "ruby_clerks/products.jpg" , :class => "img-responsive"

.row
  .col-md-9
    %div
      %table.table.table-striped.table-sm
        %thead
          %tr
            %th
              = sort_link [:office,@q], :position
              = sort_link [:office,@q], :scode
            %th
              = sort_link [:office,@q], :name
              %span.right
                %label= t(:vat)
                %input{:type => "radio", "v-model" => "alv", :value => "true"}/
                %label 0%
                %input{:type => "radio", "v-model" => "alv", :value => "false"}/
            %th
              = sort_link [:office,@q], :price
              = sort_link [:office,@q], :cost
            %th
              =t(:supplier)
              =t(:category)
            %th
              = sort_link [:office,@q], :inventory
              = t(:in_orders) if(available_inventory)
              = sort_link [:office,@q], :stock_level , t(:stock_level).split.first
              = sort_link [:office,@q], :pack_unit
        %tbody
          - @products.each do |product|
            %tr{:class => "line-#{cycle("1","2")}"}
              %td
                =link_to edit_product_path(product) do
                  = product.position
                  = product.scode
              %td.name
                = link_to product_path(product), :title => t(:show) do
                  =product.name
              %td
                %span.euro {{ price_for(#{product.id}) }}
                \|
                %span.euro {{ cost_for(#{product.id}) }}
              %td.supplier
                - if product.supplier
                  = link_to products_path("q[supplier_id_eq]" => "#{product.supplier.id}") do
                    = product.supplier.supplier_name
                - if product.category
                  = link_to products_path("q[category_id_eq]" => "#{product.category.id}") do
                    = product.category.name
              %td.inventory
                - if(available_inventory )
                  = "#{product.inventory - @product_inventory[product.id]} / #{@product_inventory[product.id]} "
                - else
                  = product.inventory
                \|
                = product.stock_level
                \|
                = product.pack_unit
                -if params[:basket]
                  = link_to t(:add_to_basket) , edit_basket_path(:id => params[:basket] , :add => product.id)
      .btn-toolbar.row
        .btn-group.pull-left
          = paginate @products
        %ul.pagination.csv
          %li
            = link_to "CSV",products_path({:format => :csv}.merge( params.to_unsafe_h))
  .col-md-3
    = search_form_for @q, :html => { :class => "form-horizontal" }, :method => :get do |f|
      .form-group
        .input
          - if params[:basket]
            = hidden_field_tag :basket , params[:basket]
            = f.text_field :name_cont, :class => "form-control" , :placeholder => t(:name)
          -else
            = f.text_field :name_cont, :class => "form-control" , :placeholder => t(:name)
      .form-group.row
        .col-md-12
          .input-group
            .input-group-addon
              =t(:in_orders)
              = radio_button_tag :in_orders , true , available_inventory

      .form-group
        .input-group
          = f.text_field :summary_cont , :class => "form-control" , :placeholder => t(:summary)
          %span.input-group-addon
            =t(:blanks)
            = f.radio_button :summary_blank , true
      .form-group
        .input-group
          = f.text_field :description_cont , :class => "form-control" , :placeholder =>  t(:description)
          %span.input-group-addon
            =t(:blanks)
            = f.radio_button :description_blank , true
      .form-group.row
        .col-md-6
          = f.text_field :ean_cont , :class => "form-control" , :placeholder => t(:ean)
        .col-md-6
          = f.text_field :scode_cont , :class => "form-control" , :placeholder => t(:scode)
      .form-group.row
        .col-md-4
          = f.label(:price)
        .col-md-4
          = f.text_field :price_gteq , :class => "form-control"
        .col-md-4
          = f.text_field :price_lteq , :class => "form-control"
        .col-md-4
          = f.label(:cost)
        .col-md-4
          = f.text_field :cost_gteq , :class => "form-control"
        .col-md-4
          = f.text_field :cost_lteq , :class => "form-control"
        .col-md-4
          = f.label(:inventory)
        .col-md-4
          = f.text_field :inventory_gteq , :class => "form-control"
        .col-md-4
          = f.text_field :inventory_lteq , :class => "form-control"
        .col-md-4
          = f.label(:stock_level)
        .col-md-4
          = f.text_field :stock_level_gteq , :class => "form-control"
        .col-md-4
          = f.text_field :stock_level_lteq , :class => "form-control"
        .col-md-4{style: "clear: left;"}
          = f.label(:pack_unit)
        .col-md-4
          = f.text_field :pack_unit_gteq , :class => "form-control"
        .col-md-4
          = f.text_field :pack_unit_lteq , :class => "form-control"
      .form-group.row
        .col-md-4
          = f.label t(:supplier)
        .col-md-8
          = f.collection_select :supplier_id_eq, Supplier.all, :id, :supplier_name, {:include_blank => true}, :class=>"form-control"
      .form-group.row
        .col-md-4
          = f.label t(:category)
        .col-md-8
          = f.collection_select :category_id_eq, Category.all, :id, :name, {:include_blank => true}, :class=>"form-control"
      = f.submit t(:filter), :class => "btn btn-success" , :id => :filter
      = link_to  t(:cancel), products_path, :class => "btn btn-warning"
.product_index_end
:ruby2js
  class ProductMethods < Vue
    options el: '.table'
    def initialize
      @products = #{@products.to_json(only: [:id , :price , :cost , :tax]).html_safe}
      @alv = "true"
    end
    def attribute_for(id , attribute)
      product = this.products.find { |product| return product.id == id }
      return id unless product
      num = product[attribute]
      num = 100 * num / (100 + product.tax) if( self.alv == "false")
      return num.toFixed(2)
    end
    def cost_for(id)
      return this.attribute_for(id , "cost")
    end
    def price_for(id)
      return this.attribute_for(id , "price")
    end
  end

app/views/products/show.html.haml
.row.product-window
  %h3
    = @product.name
    (
    %small=@product.id
    )
.row.h6
  .third
    %b= t(:scode) + " : "
    = in_place @product , :scode
  .third
    %b= t(:inventory) + " : "
    = @product.inventory
  .third
    %b= t(:stock_level) + " : "
    = in_place @product , :stock_level
  .third
    %b= t(:ean) + " : "
    = in_place @product , :ean
  .third
    %b= t(:price) + " : "
    = in_place @product , :price , display_with: lambda { |v| best_euros(v) }
  .third
    %b= t(:pack_unit) + " : "
    = in_place @product , :pack_unit
  .third
    %b= t(:position) + " : "
    = in_place @product , :position
  .third
    %b= t(:cost) + " : "
    = in_place @product , :cost , display_with: lambda { |v| best_euros(v) }
  .third
    %b= t(:tax_percent) + " : "
    = in_place @product , :tax
  .third
    %b= t(:weight) + " : "
    = in_place @product , :weight
  .third
    %b= t(:phase) + " : "
    = in_place @product , :phase
  .third
    %b= t(:dimension) + " : "
    = in_place @product , :dimension
  .half
    %b= t(:category) + " : "
    = link_to @product.category.name , category_path(@product.category) if @product.category
  .half
    %b= t(:supplier) + " : "
    = link_to @product.supplier.supplier_name ,supplier_path(@product.supplier) if @product.supplier
  .half
    %b= t(:summary) + " : "
    = in_place @product , :summary , :as => :textarea
  .half
    %b= t(:description) + " : "
    = in_place @product , :description , :as => :textarea
%br

.row.product_show_row_buttons
  .col-md-2
    = link_to t(:edit), edit_product_path(@product), :class => "btn btn-success btn-sm"
  .col-md-2
    = link_to t(:delete) , product_path(@product), :method => :delete , :class => "btn btn-danger btn-sm", :data => {  :confirm => t(:are_you_sure )}
  .col-md-2.product_show_row_end
    = link_to t(:barcode) , barcode_product_path( @product), :class => "btn btn-primary btn-sm"
  .col-md-2
    = link_to t(:new) + ' ' + t(:product) , new_product_path(copy: @product.id) , :class => "btn btn-primary bt-sm"

.product_show_end