config/routes.rb
Rails.application.routes.draw do

  root to: 'high_voltage/pages#show' , id: 'index'

  get "/blog" , to: "blog#index" , as: :blog_index
  get "/blog/*title" , to: "blog#post" , as: :blog_post

  get "sign_out" => "sessions#sign_out"
  get "sign_in"  => "sessions#sign_in"
  post "create_session"  => "sessions#create"
  match "sign_up" => "sessions#sign_up" , :via => [:get ,:post]

  resources :purchases do
    collection do
      get "search" => "purchases#index"
    end
    member do
      get :invoice, to: 'purchase_invoices#show'
      get :order
      get :receive
      get :inventory
    end
  end

  resources :baskets do
    collection do
      get "search" => "baskets#index"
    end
    member do
      get :discount
      post :ean
      get :order
      get :purchase
      get :zero
    end
  end

  resources :houses , :except => [:show , :destroy] do
    collection do
      get :products
    end
  end

  resources :orders , :except => [:edit] do
    collection do
      get "search" => "orders#index"
    end
    member do
      get "mail/:act" , :action => :mail , :as => :mail
      get :pay
      get :shipment
      get :ship
      get :deduct_only
      get :cancel
      patch :shipment
      get :invoice
      get :receipt
      get :slip
      get :reminder
      get :rakennus
      get :ecoframe
      get "finvoice_:num" , action: :finvoice , as: :finvoice
    end
  end

  resources :items do
    collection do
      get "search" => "items#index"
    end
    member do
    end
  end

  resources :categories do
    collection do
      get "search" => "categories#index"
    end
    member do
    end
  end

  resources :products do
    collection do
      get "search" => "products#index"
      get :names
    end
    member do
      get :delete
      get :barcode  #print the barcode and price on a 50x25 mm area
    end
  end

  resources :clerks do
    collection do
      get "search" => "clerks#index"
    end
    member do
    end
  end

  resources :addresses do
    collection do
      get "search" => "addresses#index"
    end
  end

  resources :suppliers do
    collection do
      get "search" => "suppliers#index"
    end
    member do
    end
  end

  get "manage/all" => "manage#all"
  get '/manage/reports' => 'manage#reports'

  get "api/purchase" => "api#purchase" , format: :json

  get "/3d/*id" => 'kolme_d#show' , as: :kolme_d
end

Rails.application.config.after_initialize do |application|
  application.routes.append do
    match '*path', via: :all, to: 'high_voltage/pages#show' , id: "404"#if Rails.production?
  end
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "btn btn-primary"} &times;
      %div= msg

app/views/layouts/application.haml
!!!
%html{:lang => (I18n.locale || I18n.default_locale)}
  %head
    %meta{:charset => "utf-8"}/
    %title= content_for?(:title) ? content_for(:title) :  "Rubydesign"
    = stylesheet_link_tag "application" ,  :media => :all
    = #javascript_include_tag "ruby_clerks"
    = csrf_meta_tags
  %body
    %link{:href => "http://fonts.googleapis.com/css?family=Roboto:400,300,100,100italic,300italic,500,700", :rel => "stylesheet", :type => "text/css"}/
    %header
      %ul.nav
        %li= link_to "Home" , root_path
        %li= ext_link "My Github", "https://github.com/rubydesign/"
        %li= ext_link "RubyX", "http://ruby-x.org"
        %li= ext_link "EcoFrame House" , "https://ecoframe.house/"
        %li= ext_link "Raisa tanssitemppeli" , "http://tanssitemppeli.fi"
        %li= ext_link "VillaTaika B&B" , "http://villataika.fi/"
        %li= ext_link "Hub Feenix" , "https://hubfeenix.fi"

    %main
      .row
        = yield
    %footer
      .row
        %ul.nav
          %li= link_to "Home" , root_path
          %li= ext_link "My Github", "https://github.com/rubydesign/"
          %li= ext_link "RubyX", "http://ruby-x.org"
          %li= ext_link "EcoFrame House" , "https://ecoframe.house/"
          %li= ext_link "Raisa tanssitemppeli" , "http://tanssitemppeli.fi"
          %li= ext_link "VillaTaika B&B" , "http://villataika.fi/"
      .row.center
        %p © Copyright Torsten Ruger 2013-20

app/views/layouts/ruby_clerks.csv.erb
<%= yield %>

app/views/layouts/ruby_clerks.haml
!!!
%html{:lang => (I18n.locale || I18n.default_locale)}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}
    %title= content_for?(:title) ? content_for(:title) :  "Office Clerk"
    = stylesheet_link_tag "ruby_clerks" ,  :media => :all
    = javascript_include_tag "ruby_clerks"
    = csrf_meta_tags
    = yield :head
  %body{:style => ""}
    .container-fluid
      .bar
        %ul
          %li{:class => params[:controller] == "products" && "active" }
            = link_to t(:products), products_path
          %li{:class => params[:controller] == "baskets" && "active" }
            = link_to t(:baskets), baskets_path
          %li{:class => params[:controller] == "orders" && "active" }
            = link_to t(:orders), orders_path
          %li{:class => params[:controller] == "purchases" && "active" }
            = link_to t(:purchases), purchases_path
          %li{:class => params[:controller] == "categories" && "active" }
            = link_to t(:categories), categories_path
          %li{:class => params[:controller] == "suppliers" && "active" }
            = link_to t(:suppliers), suppliers_path
          %li{:class => params[:controller] == "clerks" && "active" }
            = link_to t(:clerks), clerks_path
          %li{:class => params[:controller] == "manage" && "active" }
            = link_to t(:manage), manage_all_path
          %li{:class => params[:controller] == "houses" && "active" }
            = link_to t(:houses), houses_path
          - if current_clerk
            %li= link_to current_clerk.email , edit_clerk_path(current_clerk)
          %li= link_to t(:sign_out), sign_out_path
    .container-fluid
      = render "layouts/messages"

      = yield

      .row
        .col-md-12
          %br